- hosts: 192.168.43.197,192.168.43.57
  tasks:
   - name: "installation of php"
     package: 
       name: php
       state: present
    
   - name: "copying test.php"
     copy: 
       src: "/root/ansible_ws/test.php"
       dest: "/var/www/html/"
   - name: "starting webserver"
     service:
       name: "httpd"
       state: started

- hosts: localhost
  vars:
      - webserver1: 192.168.43.197
      - webserver2: 192.168.43.57
  vars_prompt:
     - name: dir
       prompt: "Enter name of directory to mount cd-rom "
       private: false
     - name: port
       prompt: "Enter port no. for web server"
       private: no
    
  tasks:
   - name: "creation of directory for mounting dvd"
     file:
       state: directory
       path: "/{{dir}}"
   - name: "mounting"
     mount:
       src: "/dev/sr0"
       fstype: iso9660
       state: mounted
       path: "{{dir}}"
       
   - name: ".repo file configuration for Appstream"
     yum_repository:
       name: "dvd1"
       description: "Appstream configuration"
       baseurl: "{{dir}}/AppStream"
       gpgcheck: no
      
   - name: ".repo file configuration for BaseOS"
     yum_repository:
       name: "dvd2"
       description: "BaseOS configuration"
       baseurl: "{{dir}}/BaseOS"
       gpgcheck: no    
       
   - name: "Installation of haproxy server"
     package:
       name: haproxy
       state: present
       
   - name: "cofiguration of haproxy server"
     template:
       dest: "/etc/haproxy/haproxy.cfg"
       src: "/root/ansible_ws/haproxy.cfg"
       
   - name: "start haproxy server"
     service:
       name: haproxy
       state: started
    







           

